apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: kcnaprep
spec: 
  replicas: 1 
  strategy: 
    type: RollingUpdate 
  selector: 
    matchLabels: 
      app: kcnaprep 
  template: 
    metadata: 
      labels: 
        app: kcnaprep 
    spec: 
      containers: 
      - name: kcnaprep 
        image: USERNAME/kcnaprep:1.0 # Replace USERNAME with the actual value
        volumeMounts:
          - name: log
            mountPath: /var/log
        ports: 
        - containerPort: 3000
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: log
