apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: kcnaprep
spec: 
  replicas: 1 
  strategy: 
    type: RollingUpdate 
  selector: 
    matchLabels: 
      app: kcnaprep 
  template: 
    metadata: 
      labels: 
        app: kcnaprep 
    spec: 
      containers: 
      - name: kcnaprep 
        image: sangramrath/kcnaprep:1.0 
        ports: 
        - containerPort: 3000
