apiVersion: v1 
kind: Pod 
metadata: 
  name: kcnaprep 
spec: 
  containers: 
  - name: kcnaprep 
    image: USERNAME/kcnaprep:1.0 # Replace USERNAME with the actual value
    ports: 
    - containerPort: 80
