apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-27T12:24:20Z"
  generateName: kcnaprep-df468c4c5-
  labels:
    app: kcnaprep
    pod-template-hash: df468c4c5
  name: kcnaprep-df468c4c5-wmw2c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kcnaprep-df468c4c5
    uid: 4381f317-9919-4fa1-a260-a9ec22181195
  resourceVersion: "45603"
  uid: b5cd43bc-313d-477d-892c-67db93f1d3b6
spec:
  containers:
  - image: sangramrath/kcnaprep:1.0
    imagePullPolicy: IfNotPresent
    name: kcnaprep
    ports:
    - containerPort: 3000
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-snpdm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-snpdm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-27T12:24:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-16T03:42:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-16T03:42:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-27T12:24:20Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7664cfce168d8b1058b70595b97b441739736fc719c5b741211214cdcc5e9af1
    image: sangramrath/kcnaprep:1.0
    imageID: docker-pullable://sangramrath/kcnaprep@sha256:377aae9530fe536fd166f0d556d5a8018f31e91afb007232d1520778f3c74d97
    lastState:
      terminated:
        containerID: docker://6040dc35e72db05cf5550576ebeabe0e66877c86f7ff163b0af3fa66d41635ee
        exitCode: 0
        finishedAt: "2024-01-28T17:32:33Z"
        reason: Completed
        startedAt: "2024-01-28T12:02:42Z"
    name: kcnaprep
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2024-04-16T03:42:22Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.16
  podIPs:
  - ip: 10.244.0.16
  qosClass: BestEffort
  startTime: "2024-01-27T12:24:20Z"
