apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: mysqldb-pv-1
  labels: 
    type: local 
spec: 
  storageClassName: manual 
  capacity: 
    storage: 10Gi 
  accessModes: 
    - ReadWriteOnce 
  hostPath: 
    path: "/data/mysql-1" 
