apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: log
  labels: 
    type: local-volume
spec: 
  storageClassName: manual 
  capacity: 
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce 
  hostPath: 
    path: "/data/log" 
